### ISSUE TITLE
About the pretrained model (pretrained_model/pretrained_model_sceneflow.ckpt) EPE:1.093, different from the result in Table 5

### ISSUE THREAD

**Issue by JiazhiLiu** [gangweiX/ACVNet#12]
A wonderful work!
I'd like to know whether the [pretrained model](pretrained_model/pretrained_model_sceneflow.ckpt) corresponds to Table 5, because I tested the pretrained model in the test dataset of SceneFlow and got the result `EPE:1.093`, further larger than the result in Table 5.

**Comment by gangweix** [comment]
Table 5 is results on KITTI, not Scene Flow. The pretrained model is for Scene Flow

**Comment by JiazhiLiu** [comment]
Are the pretrained model the best? I ran the pretrained model you provided in the test dataset of SceneFlow, but just got EPE 1.093, further larger than the result in your paper.

**Comment by gangweix** [comment]
You can use "python test_sceneflow.py" to test model on Scene Flow.

**Comment by JiazhiLiu** [comment]
Thanks for replying. I got the same result as described in your paper this time.  The previous result is caused by the compression of image files.  To save storage, I compressed the original image files from the format 'PNG'  to 'JPG'. Although there is little perceptual difference between the original and compressed, the final result diverges.
