### ISSUE TITLE
关于梯度消失和梯度爆炸

### ISSUE THREAD

**Issue by zhao976** [gangweiX/ACVNet#25]
作者您好，我在sceneflow数据集上训练ACVNet时，出现了masks[idx].float().mean() too small的警告，在冻结权值训练时出现了NaN or Inf found in input tensor的问题，判断为出现梯度爆炸，学习率设置为0.0001也没有用。请问这种情况如何解决？

**Comment by mooncii** [comment]
您好 我在自己的数据集上也出现too small的问题，请问您现在解决了吗
