### ISSUE TITLE
About the deep estimate

### ISSUE THREAD

**Issue by Xin-Li24** [gangweiX/ACVNet#36]
Hi,
Thanks for your excellent work!

I found that when i use save_disp_sceneflow.py, it can only output images of size 960 * 512. The initial size in kitti_dataset_1215.py also is a fixed value, which is 1248 * 384. If i use a picture which has a different size(eg. the pictures from middleburry or ETH3D), the result of estimate will give me a bad performance.
My first question is whether using adaptive input image size will have a negetive impact on network performance.
By the way, after I ran main_kitti.py, the result checkpoint_000599.ckpt had a bad performance in save_disp_sceneflow.py. (The result checkpoint_000063.ckpt which trained by main.py performed very well.)
My second question is whether a network training on another dataset will greatly affect the pervious result.

I would be honered if you could answer my questions. Thank you again for your excellent work!

**Comment by gangweix** [comment]
In theory, using an adaptive method has no impact on network performance. See our latest work IGEV https://github.com/gangweiX/IGEV, it can output adaptive image size.

For the second question, a network training on another dataset will greatly affect the pervious result, it's a sure thing.
