### ISSUE TITLE
关于公式(2)中的wij的一点小问题

### ISSUE THREAD

**Issue by truman1211** [gangweiX/ACVNet#6]
![image](https://user-images.githubusercontent.com/77223777/159263429-eb87ba2c-8014-480c-a388-7fd763d123b4.png)
根据公式2，对每一l_i 应该是公用同一个w_ij，但是在你们的code里却是每一个group使用同一w_ij，
因为对l1进行加权时明显有72个变量
![image](https://user-images.githubusercontent.com/77223777/159263864-171f37d1-52cb-4fda-8793-bd7553a1e958.png)

这可能是一个无关紧要的问题，我只想确认我理解是否正确。

**Comment by gangweix** [comment]
Yeah, you are right, thanks. There is a little misunderstanding in our expression.

**Comment by gangweix** [comment]
Thank you very much, we have corrected our expression in the final version of the paper.

**Comment by truman1211** [comment]
> 

不用谢，谢谢你们分享这么好的工作
