### ISSUE TITLE
关于文中的attention机制。

### ISSUE THREAD

**Issue by truman1211** [gangweiX/ACVNet#7]
我想请问一下，code里面的 attention_block.class， 是受其他paper的启发吗？

因为我看到文中对attention的描述十分简明。如果是受到其他文献的启发，可以分享一下吗？

因为我对注意力机制不是很了解，看代码有点吃力，想问一下是对[B,C,D,H,W]采用了多头注意力机制吗？

**Comment by gangweix** [comment]
Local Relation Networks for Image Recognition
